import type { Metadata } from "next";
import { lexendDex } from "@/libs/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexendDex.className}>{children}</body>
    </html>
  );
}
